### ISSUE TITLE
总是超时怎么回事儿？

### ISSUE THREAD

**Issue by NicolasKim** [bravekingzhang/flutter_chat_box#1]
如题，总是超时，但是直接访问gpt网站没问题

**Comment by bravekingzhang** [comment]
> 如题，总是超时，但是直接访问gpt网站没问题

是不是没有设置自己的 API key ，在设置中填一下试试？

**Comment by bravekingzhang** [comment]
今天抽个时间给一个设置代理服务器的功能。

**Comment by bravekingzhang** [comment]
添加了代理服务器的支持，可以设置代理，举个例子，代理服务器可以自己搜下，有很多朋友贡献
<img width="910" alt="image" src="https://user-images.githubusercontent.com/4476322/227840911-fbdae67c-028a-4190-b16f-ab856ed988bc.png">
