### ISSUE TITLE
报错RangeError (end): Invalid value: Only valid value is 0: -10

### ISSUE THREAD

**Issue by godot2d** [bravekingzhang/flutter_chat_box#17]
大佬你好，发送机器人就返回
RangeError (end): Invalid value: Only valid value is 0: -10

也没有哪里报错。是为什么鸭

**Comment by hongwen000** [comment]
![image](https://github.com/bravekingzhang/flutter_chat_box/assets/25456415/064cd237-5e35-417f-9ccb-f8f94fb193ba)
调试了一下，应该是没有API KEY。感觉输入API KEY的输入框有问题，不会保存KEY

**Comment by hongwen000** [comment]
看了一下API KEY 输入框的实现，用的是onFieldSubmitted回调。那么可能解决方法是：按一下输入法键盘上的回车

**Comment by bravekingzhang** [comment]
对，提交时保持。
