### ISSUE TITLE
代码块颜色总是变来变去

### ISSUE THREAD

**Issue by qingweiSun** [bravekingzhang/flutter_chat_box#2]

**Comment by bravekingzhang** [comment]
是因为回复内容 已 stream 的方式吗？

**Comment by qingweiSun** [comment]
应该是的，因为回复完了就好了

**Comment by bravekingzhang** [comment]
那应该是[flutter_markdown ](https://pub.dev/packages/flutter_markdown)渲染的问题，我抽空看看源码，给他们提一个pr。
