### ISSUE TITLE
直接打包 填入了key 聊天报错 RangeError(end):Invalid value: Only valid value is 0:-10

### ISSUE THREAD

**Issue by jygameclub** [bravekingzhang/flutter_chat_box#22]
![image](https://github.com/bravekingzhang/flutter_chat_box/assets/44408447/18c23586-b922-4fb6-b8af-46bfabd7ac3d)
RangeError(end):Invalid value: Only valid value is 0:-10

**Comment by bravekingzhang** [comment]
https://github.com/anasfik/openai/issues/85 这个库没处理好，已经给它提了pr了
