### ISSUE TITLE
安卓版本中gpt model的版本太少

### ISSUE THREAD

**Issue by syheliel** [bravekingzhang/flutter_chat_box#9]
model中只有gpt-3.5-turbo和gpt-3.5-turbo-0301，可以参考chatbox中的model列表

**Comment by bravekingzhang** [comment]
如果有需要可以自己增加model，基本就是配置，相信申请到gpt4的 API调用权限的人做这个还是比较easy的。

考虑到很少有人有gpt4的 API调用权限，还是不要干扰普通用户，因此就没发这个选项出来。
